### ISSUE TITLE
"Installation", .data_batch and one_hot_encode

### ISSUE THREAD

**Issue by katiejx** [HasnainRaz/SemSegPipeline#12]
Hi! Thank you for sharing your work.
I would like to ask for some issues I faced if you could please help me. First of all, the code I run is the combination of your "dataloader.py" file and your [example code](https://github.com/HasnainRaz/SemSegPipeline#example-use):

```javascript
from typing import List, Tuple

import tensorflow as tf
import random

AUTOTUNE = tf.data.experimental.AUTOTUNE


class DataLoader(object):
    """A TensorFlow Dataset API based loader for semantic segmentation problems."""

    def __init__(self, image_paths: List[str], mask_paths: List[str], image_size: Tuple[int],
                 channels: Tuple[int] = (3, 3), crop_percent: float = None, seed: int = None,
                 augment: bool = True, compose: bool = False, one_hot_encoding: bool = False, palette=None):
        """
        Initializes the data loader object
        Args:
            image_paths: List of paths of train images.
            mask_paths: List of paths of train masks (segmentation masks)
            image_size: Tuple, the final height, width of the loaded images.
            channels: Tuple of ints, first element is number of channels in images,
                      second is the number of channels in the mask image (needed to
                      correctly read the images into tensorflow and apply augmentations)
            crop_percent: Float in the range 0-1, defining percentage of image 
                          to randomly crop.
            palette: A list of RGB pixel values in the mask. If specified, the mask
                     will be one hot encoded along the channel dimension.
            seed: An int, if not specified, chosen randomly. Used as the seed for 
                  the RNG in the data pipeline.
        """
        self.image_paths = image_paths
        self.mask_paths = mask_paths
        self.palette = palette
        self.image_size = image_size
        self.augment = augment
        self.compose = compose
        self.one_hot_encoding = one_hot_encoding
        if crop_percent is not None:
            if 0.0 < crop_percent <= 1.0:
                self.crop_percent = tf.constant(crop_percent, tf.float32)
            elif 0 < crop_percent <= 100:
                self.crop_percent = tf.constant(crop_percent / 100., tf.float32)
            else:
                raise ValueError("Invalid value entered for crop size. Please use an \
                                  integer between 0 and 100, or a float between 0 and 1.0")
        else:
            self.crop_percent = None
        self.channels = channels
        if seed is None:
            self.seed = random.randint(0, 1000)
        else:
            self.seed = seed

    def _corrupt_brightness(self, image, mask):
        """
        Radnomly applies a random brightness change.
        """
        cond_brightness = tf.cast(tf.random.uniform(
            [], maxval=2, dtype=tf.int32), tf.bool)
        image = tf.cond(cond_brightness, lambda: tf.image.random_brightness(
            image, 0.1), lambda: tf.identity(image))
        return image, mask


    def _corrupt_contrast(self, image, mask):
        """
        Randomly applies a random contrast change.
        """
        cond_contrast = tf.cast(tf.random.uniform(
            [], maxval=2, dtype=tf.int32), tf.bool)
        image = tf.cond(cond_contrast, lambda: tf.image.random_contrast(
            image, 0.1, 0.8), lambda: tf.identity(image))
        return image, mask


    def _corrupt_saturation(self, image, mask):
        """
        Randomly applies a random saturation change.
        """
        cond_saturation = tf.cast(tf.random.uniform(
            [], maxval=2, dtype=tf.int32), tf.bool)
        image = tf.cond(cond_saturation, lambda: tf.image.random_saturation(
            image, 0.1, 0.8), lambda: tf.identity(image))
        return image, mask


    def _crop_random(self, image, mask):
        """
        Randomly crops image and mask in accord.
        """
        cond_crop_image = tf.cast(tf.random.uniform(
            [], maxval=2, dtype=tf.int32, seed=self.seed), tf.bool)

        shape = tf.cast(tf.shape(image), tf.float32)
        h = tf.cast(shape[0] * self.crop_percent, tf.int32)
        w = tf.cast(shape[1] * self.crop_percent, tf.int32)

        comb_tensor = tf.concat([image, mask], axis=2)
        
        comb_tensor = tf.cond(cond_crop_image, lambda: tf.image.random_crop(
            comb_tensor, [h, w, self.channels[0] + self.channels[1]], seed=self.seed), lambda: tf.identity(comb_tensor))
        image, mask = tf.split(comb_tensor, [self.channels[0], self.channels[1]], axis=2)

        return image, mask


    def _flip_left_right(self, image, mask):
        """
        Randomly flips image and mask left or right in accord.
        """
        comb_tensor = tf.concat([image, mask], axis=2)
        comb_tensor = tf.image.random_flip_left_right(comb_tensor, seed=self.seed)
        image, mask = tf.split(comb_tensor, [self.channels[0], self.channels[1]], axis=2)

        return image, mask


    def _resize_data(self, image, mask):
        """
        Resizes images to specified size.
        """
        image = tf.image.resize(image, self.image_size)
        mask = tf.image.resize(mask, self.image_size, method="nearest")
        
        return image, mask


    def _parse_data(self, image_paths, mask_paths):
        """
        Reads image and mask files depending on
        specified exxtension.
        """
        image_content = tf.io.read_file(image_paths)
        mask_content = tf.io.read_file(mask_paths)

        images = tf.image.decode_jpeg(image_content, channels=self.channels[0])
        masks = tf.image.decode_jpeg(mask_content, channels=self.channels[1])

        return images, masks


    def _one_hot_encode(self, image, mask):
        """
        Converts mask to a one-hot encoding specified by the semantic map.
        """
        one_hot_map = []
        for colour in self.palette:
            class_map = tf.reduce_all(tf.equal(mask, colour), axis=-1)
            one_hot_map.append(class_map)
        one_hot_map = tf.stack(one_hot_map, axis=-1)
        one_hot_map = tf.cast(one_hot_map, tf.float32)
        
        return image, one_hot_map

    @tf.function
    def _map_function(self, images_path, masks_path):
        image, mask = self._parse_data(images_path, masks_path)

        def _augmentation_func(image_f, mask_f):
            if self.augment:
                if self.compose:
                    image_f, mask_f = self._corrupt_brightness(image_f, mask_f)
                    image_f, mask_f = self._corrupt_contrast(image_f, mask_f)
                    image_f, mask_f = self._corrupt_saturation(image_f, mask_f)
                    image_f, mask_f = self._crop_random(image_f, mask_f)
                    image_f, mask_f = self._flip_left_right(image_f, mask_f)
                else:
                    options = [self._corrupt_brightness,
                               self._corrupt_contrast,
                               self._corrupt_saturation,
                               self._crop_random,
                               self._flip_left_right]
                    augment_func = random.choice(options)
                    image_f, mask_f = augment_func(image_f, mask_f)

            if self.one_hot_encoding:
                if self.palette is None:
                    raise ValueError('No Palette for one-hot encoding specified in the data loader! \
                                      please specify one when initializing the loader.')
                image_f, mask_f = self._one_hot_encode(image_f, mask_f)

            image_f, mask_f = self._resize_data(image_f, mask_f)
            return image_f, mask_f
        return tf.py_function(_augmentation_func, [image, mask], [tf.float32, tf.uint8])

    def data_batch(self, batch_size, shuffle=False):
        """
        Reads data, normalizes it, shuffles it, then batches it, returns a
        the next element in dataset op and the dataset initializer op.
        Inputs:
            batch_size: Number of images/masks in each batch returned.
            augment: Boolean, whether to augment data or not.
            shuffle: Boolean, whether to shuffle data in buffer or not.
            one_hot_encode: Boolean, whether to one hot encode the mask image or not.
                            Encoding will done according to the palette specified when
                            initializing the object.
        Returns:
            data: A tf dataset object.
        """

        # Create dataset out of the 2 files:
        data = tf.data.Dataset.from_tensor_slices((self.image_paths, self.mask_paths))

        # Parse images and labels
        data = data.map(self._map_function, num_parallel_calls=AUTOTUNE)

        if shuffle:
            # Prefetch, shuffle then batch
            data = data.prefetch(AUTOTUNE).shuffle(random.randint(0, len(self.image_paths))).batch(batch_size)
        else:
            # Batch and prefetch
            data = data.batch(batch_size).prefetch(AUTOTUNE)

        return data



import os

MAIN_PATH      = 'D:/code/test12/'
IMAGE_DIR_PATH = MAIN_PATH+'VOC2012/JPEGImages/'
MASK_DIR_PATH  = MAIN_PATH+'VOC2012/SegmentationObject/'
BATCH_SIZE     = 4

# create list of PATHS
image_paths = [os.path.join(IMAGE_DIR_PATH, x) for x in os.listdir(IMAGE_DIR_PATH) if x.endswith('.jpg')]
mask_paths = [os.path.join(MASK_DIR_PATH, x) for x in os.listdir(MASK_DIR_PATH) if x.endswith('.png')]

Initialize the dataloader object
dataset = DataLoader(image_paths=image_paths,
                      mask_paths=mask_paths,
                      image_size=(256, 256),
                      crop_percent=0.8,
                      channels=(3, 1),
                      augment=True,
                      compose=False,
                      seed=47)

# Parse the images and masks, and return the data in batches, augmented optionally.
dataset = dataset.data_batch(batch_size=BATCH_SIZE,shuffle=True)

# Initialize the data queue
for image, mask in dataset:
    # Do whatever you want now
```

1. It's probably a silly question but I'm quite new in python: in order to "import" something (like `from dataloader import DataLoader`), you have to have installed it first, right? In this case how the "installation" is done? What I did (which I think is not the right approach) is to copy the code of "dataloader.py" and paste it at the beginning of my code (your code actually, your [example](https://github.com/HasnainRaz/SemSegPipeline#example-use)). So I run the content of "dataloader.py" and then the rest of the code.

2. I downloaded the PASCAL VOC dataset and added the paths in the code (IMAGE_DIR_PATH & MASK_DIR_PATH). When running the line `dataset = dataset.data_batch(batch_size=BATCH_SIZE,shuffle=True)`, I get this error:
```javascript
Traceback (most recent call last):

  File "<ipython-input-15-d91f0c5e698b>", line 1, in <module>
    dataset = dataset.data_batch(batch_size=BATCH_SIZE,shuffle=True)

  File "<ipython-input-1-83f210ebd7b2>", line 202, in data_batch
    data = tf.data.Dataset.from_tensor_slices((self.image_paths, self.mask_paths))

  File "C:\Anaconda3\envs\spyder\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 682, in from_tensor_slices
    return TensorSliceDataset(tensors)

  File "C:\Anaconda3\envs\spyder\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 3010, in __init__
    batch_dim.assert_is_compatible_with(tensor_shape.Dimension(

  File "C:\Anaconda3\envs\spyder\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 279, in assert_is_compatible_with
    raise ValueError("Dimensions %s and %s are not compatible" %

ValueError: Dimensions 17125 and 2913 are not compatible
```

3. I want to use "one_hot_encode", so according to "dataloader.py", in lines 190-196, I have to add `one_hot_encode=True` as argument in `dataset.data_batch()`, is this right? When I do that, i.e. `dataset = dataset.data_batch(batch_size=BATCH_SIZE,shuffle=True,one_hot_encode=True)` and run this line, I get this error:
```javascript
Traceback (most recent call last):

  File "<ipython-input-16-ff6e561e9f62>", line 1, in <module>
    dataset = dataset.data_batch(batch_size=BATCH_SIZE,shuffle=True,one_hot_encode=True)

TypeError: data_batch() got an unexpected keyword argument 'one_hot_encode'
```

**Thank you in advance for your time and any possible help.**

**Comment by HasnainRaz** [comment]
Hey,

1. What you did was correct. This repo is not offered as an installable package. You can just copy the code here and use it in your project as you wish. As long as the dataloader.py file is in the same folder as the rest of your code, you would be able to import and use it.

2. I assume it's because you image and mask paths are not paired. You need to ensure that the first element in the image_path list, and the first element of the mask path list form the same image mask pairs. Same goes for the rest of the elements. Indexes in both lists should be paired. You can do this easily by doing this:
```python
import os

image_dir = 'path/to/image/directory'
mask_dir = 'path/to/mask/directory'

mask_paths = [os.path.join(mask_dir, x) for x in os.listdir(mask_dir)]
image_paths = [os.path.join(image_dir, os.path.basename(x)) for x in mask_paths]
```
Please take care that the file extension is correct for image and masks. If you need to change image extensions to jpg (or anything else), use this line instead:
```python
image_paths =  [os.path.join(image_dir, os.path.basename(x)[:-4] + '.jpg') for x in mask_paths]
```
This should solve your problem hopefully.

3. You have to set "one_hot_encoding" to True when initializing the class, not when calling the data_batch function.
```python
dataset = DataLoader(image_paths=image_paths,
                      mask_paths=mask_paths,
                      image_size=(256, 256),
                      crop_percent=0.8,
                      channels=(3, 1),
                      augment=True,
                      compose=False,
                      one_hot_encoding=True,
                      seed=47)
```
